CREATE DATABASE FORGEURSELFOPENBANKING;

USE FORGEURSELFOPENBANKING;


CREATE TABLE "USER"(
ID INT IDENTITY(1,1),
FIRST_NAME VARCHAR(20),
MIDDLE_NAME   VARCHAR(256),
LAST_NAME VARCHAR(20),
EMAIL VARCHAR(20),
PASSWORD VARCHAR(256),
PRIMARY KEY (ID)
);

CREATE TABLE "CUSTOMER_HOME_LOAN_APPLN"
(
  ID INT IDENTITY(1,1),
  FULL_NAME  VARCHAR(256),
  APPLN_NAME  VARCHAR(256),
  EMAIL VARCHAR(100),
  PHONE_NUMBER VARCHAR(10),
  ADDRESS VARCHAR(256),
  OWN_RENT VARCHAR(20),
  SELL_HOME VARCHAR(20),
  PRE_QUALIFIED VARCHAR(20),
  COMMENTS VARCHAR(256),
  MAIL_STATUS VARCHAR(20) DEFAULT 'P',
  PRIMARY KEY (ID)
);





SELECT * FROM USER;


DROP TABLE USER;

DROP DATABASE FORGEURSELFOPENBANKING;
